name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1
    - name: Setup VSTest 
      uses: darenm/Setup-VSTest@v1
    - name: Use NuGet 5.2.0
      uses: nuget/setup-nuget@v1
    - name: Build solution
      run:  msbuild.exe .\TestApp.sln /t:restore
    - name: Run Unit Tests
      run: vstest.console.exe .\build\TestApp.UnitTests.dll 
